### ISSUE TITLE
Atom feeds not working

### ISSUE THREAD

**Issue by clawoflight** [kellerben/dudle#20]
I am trying to enable the atom feeds.

I successfully installed the required gem and have set the env variable RUBYLIB to my installation path in the .htaccess.
However, the execution of atom.cgi fails every time with this error:

```
[Sat Jan 09 07:47:28.950055 2016] [cgid:error] [pid 11831:tid 140437142550272] [client 127.0.0.1:44370] End of script output before headers: atom.cgi                                                                                       │
/var/www/html/dudle/atom.rb:31:in `<top (required)>': uninitialized constant Atom (NameError)                                                                                                                                               │
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                                                                                                                        │
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'                                                                                                                                                        │
        from /var/www/html/dudle/bday-2016/atom.cgi:23:in `<main>'
```

**Comment by kellerben** [comment]
I think this is a problem with ruby 2.1. I will investigate this.

**Comment by clawoflight** [comment]
Thanks :)

**Comment by kellerben** [comment]
fixed in 8d2c1ab

**Comment by clawoflight** [comment]
@kellerben
It's still not working.
Looking at line 31, which is the

**Comment by kellerben** [comment]
you are right…
Line 23 didn't failed. Therefore you have something installed which has the name atom.rb. can you give me the output of this
```
$ gem search -l ratom
*** LOCAL GEMS ***
ratom (0.9.0)
```

**Comment by clawoflight** [comment]
I don't have a lot of gems anyway, so I'll just give you all:

```
$ gem list --local
*** LOCAL GEMS ***
bigdecimal (1.2.4)
gettext (3.1.2)
io-console (0.4.2)
json (1.8.1)
libxml-ruby (2.8.0)
locale (2.1.0)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
ratom (0.9.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
text (1.3.0)
```

**Comment by kellerben** [comment]
may it be for any reason, that ruby loads another file with the name ```atom.rb``` and not the one coming from the ratom gem?
Can you do a ```find -name atom.rb``` inside your RUBYLIB (i.e. anything what is inside the ruby variable ```$:```

**Comment by clawoflight** [comment]
I get this:

```
/usr/lib/ruby/2.1.0/rss/dublincore/atom.rb
/usr/lib/ruby/2.1.0/rss/atom.rb
/usr/lib/ruby/2.1.0/rss/maker/atom.rb
```

**Comment by kellerben** [comment]
can you check this: ```find /var/lib/gems/2.1.0 -iname atom.rb```

**Comment by clawoflight** [comment]
```
$ find /var/lib/gems/2.1.0 -iname atom.rb
/var/lib/gems/2.1.0/gems/ratom-0.9.0/lib/atom.rb
```

That looks good to me...

**Comment by ktalik** [comment]
I'm having really similar issue (already contacted you by e-mail):

```
[Sun Feb 07 22:24:15.817582 2016] [cgi:error] [pid 27483] [client 10.1.123.95:41026] AH01215: /var/www/html/dudle/dudle.rb:132:in `initialize': undefined method `name' for false:FalseClass (NoMethodError)
[Sun Feb 07 22:24:15.817616 2016] [cgi:error] [pid 27483] [client 10.1.123.95:41026] AH01215: \tfrom /var/www/html/dudle/asddd/edit_columns.cgi:34:in `new'
[Sun Feb 07 22:24:15.817626 2016] [cgi:error] [pid 27483] [client 10.1.123.95:41026] AH01215: \tfrom /var/www/html/dudle/asddd/edit_columns.cgi:34:in `<main>'
[Sun Feb 07 22:24:15.818210 2016] [cgi:error] [pid 27483] [client 10.1.123.95:41026] End of script output before headers: edit_columns.cgi
```

Maybe [this](http://unix.stackexchange.com/a/123869) is the reason somewhere?

**Comment by kellerben** [comment]
your link has nohting to do with your problem and your problem is completely different to the one described here. I have no idea why the ruby atom implementation of clawoflight does not behave like mine…

**Comment by kellerben** [comment]
Still a problem? I have no idea why this happens and it works on all my installations…
